worker_processes auto;

events {
    worker_connections 1024;  # Adjust to the number of connections per worker
}

http {
    # access_log off;
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log crit;

    # Adjust buffer sizes
    # Increase if you're allowing large uploads
    client_max_body_size 5M;
    # If you're handling long headers (e.g., cookies)
    large_client_header_buffers 4 16k;
    proxy_buffers 16 16k;
    proxy_busy_buffers_size 32k;
    proxy_max_temp_file_size 0;  # Disable temporary files for proxy

    gzip on;
    # Compression level, higher means more CPU but smaller size
    gzip_comp_level 6;
    # Enable Vary header for caching proxies
    gzip_vary on;
    gzip_types text/plain application/javascript application/json text/css application/xml text/xml application/xml+rss;
    gzip_proxied any;

    keepalive_timeout 65s; # Keep connections alive for 65 seconds
    tcp_nopush on;         # Reduce overhead by sending full packets
    tcp_nodelay on;        # Ensure packets are sent immediately
    sendfile on;           # Enable sendfile() for sending large files more efficiently
    aio threads;           # Enable Asynchronous I/O for better performance on large files

    include       mime.types;
    default_type  application/octet-stream;

    include /etc/nginx/conf.d/*.conf;  # This is the key part! Includes all .conf files in conf.d
}
